package com.company.Dao;

import com.company.entity.*;

import java.util.Scanner;
import java.util.LinkedList;

public interface IMyDAO {
    public void addPlant(Plant _Plant);
    public void addPlant(Flowering _Flowering);
    public void addPlant(Orchids _Orchid);
    public void addPlant(Cactus _Cactus);
    public void addPlant(FernLike _FernLike);
    public void addPlant(Fern _Fern);
    public void addFamily(Family _Family);
    public void addFertilizer(Fertilizer _Fertilizer);
    public void addSoil(Soil _Soil);
    public void addPotType(PotType _PotType);
    public void addInflorescenceType(InflorescenceType _InflorescenceType);
    public void addLeafStructure(LeafStructure _LeafStructure);
    public void addSort(Sort _Sort);
    public void deletePlant(int id);
    public void deleteFlowering(int id);
    public void deleteOrchid(int id);
    public void deleteCactus(int id);
    public void deleteFernLike(int id);
    public void deleteFern(int id);
    public void deleteFamily(int id);
    public void deleteFertilizer(int id);
    public void deleteSoil(int id);
    public void deleteSort(int id);
    public void deletePotTye(int id);
    public void deleteInflorescenceType(int id);
    public void deleteLeafStructure(int id);
    public LinkedList<Soil> updateSoil(int id,String _Title);
    public LinkedList<Sort> updateSort(int id,String _Title);
    public LinkedList<Fertilizer> updateFertilizer(int id,String _Title);
    public LinkedList<Family> updateFamily(int id,String _Title);
    public LinkedList<PotType> updatePotType(int id,String _Title);
    public LinkedList<InflorescenceType> updateInflorescenceType(int id,String _Title);
    public LinkedList<LeafStructure> updateLeafStructure(int id,String _Title);
    public LinkedList<Plant> updatePlantTitle(int id,String _Title);
    public LinkedList<Plant> updateFloweringTitle(int id,String _Title);
    public LinkedList<Plant> updateOrchidsTitle(int id,String _Title);
    public LinkedList<Plant> updateCactusTitle(int id,String _Title);
    public LinkedList<Plant> updateFernLikeTitle(int id,String _Title);
    public LinkedList<Plant> updateFernTitle(int id,String _Title);
    public LinkedList<Plant> getPlant();
    public LinkedList<Flowering> getFlowering();
    public LinkedList<Orchids> getOrchids();
    public LinkedList<Cactus> getCactus();
    public LinkedList<FernLike> getFernLike();
    public LinkedList<Fern> getFern();
    public LinkedList<Soil> GetAllSoil();
    public LinkedList<Sort> GetAllSort();
    public LinkedList<Fertilizer> GetAllFertilizer();
    public LinkedList<Family> GetAllFamily();
    public LinkedList<PotType> GetAllPotType();
    public LinkedList<InflorescenceType> GetAllInflorescenceType();
    public LinkedList<LeafStructure> GetAllLeafStructure();
    public LinkedList<Family> search_FamilyName(String _Title);
    public LinkedList<Family> search_FamilyId(int id);
    public LinkedList<Fertilizer> search_FertilizerName(String _Title);
    public LinkedList<Fertilizer> search_FertilizerId(int id);
    public LinkedList<Soil> search_SoilName(String _Title);
    public LinkedList<Soil> search_SoilId(int id);
    public LinkedList<PotType> search_PotTypeName(String _Title);
    public LinkedList<PotType> search_PotTypeId(int id);
    public LinkedList<InflorescenceType> search_InflorescenceTypeName(String _Title);
    public LinkedList<InflorescenceType> search_InflorescenceTypeId(int id);
    public LinkedList<LeafStructure> search_LeafStructureName(String _Title);
    public LinkedList<LeafStructure> search_LeafStructureId(int id);
    public LinkedList<Sort> search_SortName(String _Title);
    public LinkedList<Sort> search_SortId(int id);
    public LinkedList<Plant> search_PlantName(String _Title);
    public LinkedList<Plant> search_PlantId(int id);
    public LinkedList<Plant> search_FloweringName(String _Title);
    public LinkedList<Plant> search_FloweringId(int id);
    public LinkedList<Plant> search_CactusName(String _Title);
    public LinkedList<Plant> search_CactusId(int id);
    public LinkedList<Plant> search_OrchidName(String _Title);
    public LinkedList<Plant> search_OrchidId(int id);
    public LinkedList<Plant> search_FernLikeName(String _Title);
    public LinkedList<Plant> search_FernLikeId(int id);
    public LinkedList<Plant> search_FernName(String _Title);
    public LinkedList<Plant> search_FernId(int id);
}
